{
 "title": "Server Status",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "host_server",
    "label": "Metrics Server Apache",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "host_apache_service",
    "label": "Metrics Service Apache",
    "query": {
     "query": "label_values(apache_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "LOAD BALANCER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server status - Load Balancer",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "up{instance=\"172.16.163.2:9100\",job=\"load_balancer\"}"
      }
     ]
    },
    {
     "title": "RAM - Load Balancer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.16.163.2:9100\",job=\"load_balancer\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.16.163.2:9100\",job=\"load_balancer\"} - node_memory_MemFree_bytes{instance=\"172.16.163.2:9100\",job=\"load_balancer\"} - (node_memory_Cached_bytes{instance=\"172.16.163.2:9100\",job=\"load_balancer\"} + node_memory_Buffers_bytes{instance=\"172.16.163.2:9100\",job=\"load_balancer\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"172.16.163.2:9100\",job=\"load_balancer\"} + node_memory_Buffers_bytes{instance=\"172.16.163.2:9100\",job=\"load_balancer\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"172.16.163.2:9100\",job=\"load_balancer\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"172.16.163.2:9100\",job=\"load_balancer\"} - node_memory_SwapFree_bytes{instance=\"172.16.163.2:9100\",job=\"load_balancer\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "HTTP Traffic - Load Balancer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_http_response_size_bytes{instance=~\"172.16.163.2:4040\"}[5m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "NGINX status - MariaDB",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "nginx_up{instance=\"172.16.163.2:9113\",job=\"load_balancer\"}"
      }
     ]
    },
    {
     "title": "Active Connections - Load Balancer",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 3, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "nginx_connections_active{instance=~\"172.16.163.2:9113\"}",
       "legendFormat": "{{instance}} active"
      },
      {
       "expr": "nginx_connections_reading{instance=~\"172.16.163.2:9113\"}",
       "legendFormat": "{{instance}} reading"
      },
      {
       "expr": "nginx_connections_waiting{instance=~\"172.16.163.2:9113\"}",
       "legendFormat": "{{instance}} waiting"
      },
      {
       "expr": "nginx_connections_writing{instance=~\"172.16.163.2:9113\"}",
       "legendFormat": "{{instance}} writing"
      }
     ]
    },
    {
     "title": "Processed connections - Load Balancer",
     "type": "graph",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "Connections (rate)" }
     ],
     "targets": [
      {
       "expr": "irate(nginx_connections_accepted{instance=~\"172.16.163.2:9113\"}[5m])",
       "legendFormat": "{{instance}} accepted"
      },
      {
       "expr": "irate(nginx_connections_handled{instance=~\"172.16.163.2:9113\"}[5m])",
       "legendFormat": "{{instance}} handled"
      }
     ]
    },
    {
     "title": "CPU - Load Balancer",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=\"172.16.163.2:9100\",job=\"load_balancer\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"172.16.163.2:9100\",job=\"load_balancer\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"172.16.163.2:9100\",job=\"load_balancer\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Traffic Entrance - Load Balancer",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=\"172.16.163.2:9100\",job=\"load_balancer\"}[5m])*8",
       "legendFormat": "recv {{device}}"
      }
     ]
    },
    {
     "title": "Status codes per second - Load Balancer",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_http_response_count_total{instance=~\"172.16.163.2:4040\"}[1m])) by (status) != 0",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "APACHE - FRONT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server status - Apache 1",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "up{instance=\"$host_server\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "RAM - Apache 1",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$host_server\",job=\"$job\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$host_server\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$host_server\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$host_server\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$host_server\",job=\"$job\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$host_server\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$host_server\",job=\"$job\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$host_server\",job=\"$job\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$host_server\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$host_server\",job=\"$job\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Current total kbytes sent - Apache 1",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 2 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "rate(apache_sent_kilobytes_total{instance=~\"$host_apache_service\"}[5m])",
       "legendFormat": "Kilobytes Sent"
      }
     ]
    },
    {
     "title": "Apache2 status - Apache 1",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "apache_up{instance=\"$host_apache_service\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Current total apache accesses - Apache 1",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 3, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(apache_accesses_total{instance=~\"$host_apache_service\"}[5m])",
       "legendFormat": "Accesses"
      }
     ]
    },
    {
     "title": "Apache worker statuses - Apache 1",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "apache_workers{instance=~\"$host_apache_service\"}\n",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "Uptime - Apache 1",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "expr": "apache_uptime_seconds_total{instance=~\"$host_apache_service\"}"
      }
     ]
    },
    {
     "title": "CPU - Apache 1",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=\"$host_server\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$host_server\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$host_server\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Apache scoreboard statuses - Apache 1",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "apache_scoreboard{instance=~\"$host_apache_service\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server status - NFS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "up{instance=\"172.16.163.111:9100\",job=\"nfs\"}"
      }
     ]
    },
    {
     "title": "RAM - NFS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 3, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\"} - node_memory_MemFree_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\"} - (node_memory_Cached_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\"} + node_memory_Buffers_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\"} + node_memory_Buffers_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\"} - node_memory_SwapFree_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Disk Space Used Basic - NFS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Uptime - NFS",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 49 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"172.16.163.111:9100\",job=\"nfs\"} - node_boot_time_seconds{instance=\"172.16.163.111:9100\",job=\"nfs\"}"
      }
     ]
    },
    {
     "title": "CPU - NFS",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=\"172.16.163.111:9100\",job=\"nfs\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"172.16.163.111:9100\",job=\"nfs\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"172.16.163.111:9100\",job=\"nfs\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "NFS Packets Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 3, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_nfsd_packets_total{instance=\"172.16.163.111:9100\",job=\"nfs\",proto=\"tcp\"}",
       "legendFormat": "Packets Total"
      }
     ]
    },
    {
     "title": "NFS Connections Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_nfsd_connections_total{instance=\"172.16.163.111:9100\",job=\"nfs\"}",
       "legendFormat": "Total connections"
      }
     ]
    },
    {
     "title": "Storage (Disk 2) - NFS",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{device=\"/dev/sdb1\",fstype=\"ext4\",instance=\"172.16.163.111:9100\",job=\"nfs\",mountpoint=\"/srv/filer01\"}",
       "legendFormat": "Free Storage"
      },
      {
       "expr": "node_filesystem_size_bytes{instance=\"172.16.163.111:9100\",job=\"nfs\",mountpoint=\"/srv/filer01\"}",
       "legendFormat": "Total Storage"
      }
     ]
    }
   ]
  },
  {
   "title": "GESTION",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server status - Gestion",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "up{instance=\"172.16.163.149:9100\",job=\"gestion\"}"
      }
     ]
    },
    {
     "title": "RAM - Gestion",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.16.163.149:9100\",job=\"gestion\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.16.163.149:9100\",job=\"gestion\"} - node_memory_MemFree_bytes{instance=\"172.16.163.149:9100\",job=\"gestion\"} - (node_memory_Cached_bytes{instance=\"172.16.163.149:9100\",job=\"gestion\"} + node_memory_Buffers_bytes{instance=\"172.16.163.149:9100\",job=\"gestion\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"172.16.163.149:9100\",job=\"gestion\"} + node_memory_Buffers_bytes{instance=\"172.16.163.149:9100\",job=\"gestion\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"172.16.163.149:9100\",job=\"gestion\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"172.16.163.149:9100\",job=\"gestion\"} - node_memory_SwapFree_bytes{instance=\"172.16.163.149:9100\",job=\"gestion\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "CPU - Gestion",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=\"172.16.163.149:9100\",job=\"gestion\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"172.16.163.149:9100\",job=\"gestion\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"172.16.163.149:9100\",job=\"gestion\"}) by (cpu))"
      }
     ]
    }
   ]
  },
  {
   "title": "FTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server status - FTP",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "up{instance=\"172.16.163.21:9100\",job=\"ftp\"}"
      }
     ]
    },
    {
     "title": "RAM - FTP",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 3, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.16.163.21:9100\",job=\"ftp\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.16.163.21:9100\",job=\"ftp\"} - node_memory_MemFree_bytes{instance=\"172.16.163.21:9100\",job=\"ftp\"} - (node_memory_Cached_bytes{instance=\"172.16.163.21:9100\",job=\"ftp\"} + node_memory_Buffers_bytes{instance=\"172.16.163.21:9100\",job=\"ftp\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"172.16.163.21:9100\",job=\"ftp\"} + node_memory_Buffers_bytes{instance=\"172.16.163.21:9100\",job=\"ftp\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"172.16.163.21:9100\",job=\"ftp\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"172.16.163.21:9100\",job=\"ftp\"} - node_memory_SwapFree_bytes{instance=\"172.16.163.21:9100\",job=\"ftp\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "CPU - FTP",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=\"172.16.163.21:9100\",job=\"ftp\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"172.16.163.21:9100\",job=\"ftp\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"172.16.163.21:9100\",job=\"ftp\"}) by (cpu))"
      }
     ]
    }
   ]
  },
  {
   "title": "MARIA DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server status - MariaDB",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "up{instance=\"172.16.163.36:9100\",job=\"mariadb\"}"
      }
     ]
    },
    {
     "title": "RAM - MariaDB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 3, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.16.163.36:9100\",job=\"mariadb\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"172.16.163.36:9100\",job=\"mariadb\"} - node_memory_MemFree_bytes{instance=\"172.16.163.36:9100\",job=\"mariadb\"} - (node_memory_Cached_bytes{instance=\"172.16.163.36:9100\",job=\"mariadb\"} + node_memory_Buffers_bytes{instance=\"172.16.163.36:9100\",job=\"mariadb\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"172.16.163.36:9100\",job=\"mariadb\"} + node_memory_Buffers_bytes{instance=\"172.16.163.36:9100\",job=\"mariadb\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"172.16.163.36:9100\",job=\"mariadb\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"172.16.163.36:9100\",job=\"mariadb\"} - node_memory_SwapFree_bytes{instance=\"172.16.163.36:9100\",job=\"mariadb\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Recent Connections - MariaDB",
     "type": "table",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 78 },
     "targets": [
      {
       "rawSql": "SELECT\n  accessed AS \"TIME\",\n  userid AS \"USERS\"\nFROM ftpuser\nORDER BY accessed DESC"
      }
     ]
    },
    {
     "title": "MariaDB status - MariaDB",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mysql_up{instance=\"172.16.163.36:9104\",job=\"mariadb\"}"
      }
     ]
    },
    {
     "title": "Connections - MariaDB",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 3, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"172.16.163.36:9104\"}[5s])  or mysql_global_status_threads_connected{instance=\"172.16.163.36:9104\"} )",
       "legendFormat": "Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_max_used_connections{instance=\"172.16.163.36:9104\"}",
       "legendFormat": "Max Used Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_max_connections{instance=\"172.16.163.36:9104\"}",
       "legendFormat": "Max Connections"
      }
     ]
    },
    {
     "title": "Network Traffic - MariaDB",
     "type": "graph",
     "gridPos": { "h": 12, "w": 13, "x": 11, "y": 85 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_bytes_received{instance=\"172.16.163.36:9104\"}[5s]) or irate(mysql_global_status_bytes_received{instance=\"172.16.163.36:9104\"}[5m])",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_bytes_sent{instance=\"172.16.163.36:9104\"}[5s]) or irate(mysql_global_status_bytes_sent{instance=\"172.16.163.36:9104\"}[5m])",
       "legendFormat": "Outbound"
      }
     ]
    },
    {
     "title": "CPU - MariaDB",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=\"172.16.163.36:9100\",job=\"mariadb\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"172.16.163.36:9100\",job=\"mariadb\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"172.16.163.36:9100\",job=\"mariadb\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Access denied - MariaDB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mysql_global_status_access_denied_errors{instance=\"172.16.163.36:9104\",job=\"mariadb\"}",
       "legendFormat": "Access denied errors"
      }
     ]
    },
    {
     "title": "Top Command Counters - MariaDB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5, rate(mysql_global_status_commands_total{instance=\"172.16.163.36:9104\"}[5s])>0) or topk(5, irate(mysql_global_status_commands_total{instance=\"172.16.163.36:9104\"}[5m])>0)",
       "legendFormat": "Com_{{ command }}"
      }
     ]
    }
   ]
  }
 ]
}